name: tmodel_dart
version: 0.1.0
description: A dart library that helps you to manage model (blueprint) objects.
homepage: https://github.com/tyrcord/tmodel_dart
issue_tracker: https://github.com/tyrcord/tmodel_dart/issues

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  equatable: ^1.2.5

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
  dart_code_metrics: ^2.3.1
