name: tmodel_dart
version: 0.2.1
description: A dart library that helps you to manage model (blueprint) objects.
homepage: https://github.com/tyrcord/tmodel_dart
issue_tracker: https://github.com/tyrcord/tmodel_dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  dart_code_metrics: ^3.2.2
