name: tmodel_dart
version: 0.3.0
description: A dart library that helps you to manage model (blueprint) objects.
homepage: https://github.com/tyrcord/tmodel_dart
issue_tracker: https://github.com/tyrcord/tmodel_dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  dart_code_metrics: ^4.0.1